create schema oyo;
use oyo;

#List all hotel names?
select*from oyo_db;

# count the No.of oyo Hotels ?
select count(*) as 'Total oyo Hotels' from oyo_db;#460

# List the top 10 oyo hotels with Average Highest Rating?
select Hotel_Name,avg(Rating) as 'Avg Rating' 
from oyo_db
group by Hotel_Name
order by 'Avg Rating'DESC
limit 10;

# Determine the No.of oyo hotels in each city
select Place,count(*) as 'No_of_Hotels'
from oyo_db
group by place
order by No_of_Hotels desc;

#Determine the count of oyo hotel rooms have Air Conditioning?
select count(*)from oyo_db
where "Air Conditioning" ='YES';

#Calculate the Total Revenue Generated by oyo hotels in each city
select place,sum(Price) as 'Revenue_Generated'from oyo_db
group by place
order by Revenue_Generated Desc;

#Identify oyo hotel that have received more than 90% of positive reviews?
Select
  Hotel_Name,
  SUM(CASE WHEN Rating >= 1500 THEN 1 ELSE 0 END) / COUNT(*) * 100 AS Positive_Review_Percentage
from
  oyo_db
group by 
  Hotel_Name
having
  Positive_Review_Percentage >= 90;
  
#Determine the AVG Price of oyo hotel in each city along with their Population
  select Place,avg(Price)as 'AVG_Price',Population 
  from oyo_db
  Group by Place,Population;
  
#Find hotels with a price less than 3000 and with more No.of ratings?
SELECT Hotel_Name,price,Rating
FROM oyo_db
WHERE Price<3000 and Rating> 2000 
order by Rating Desc;

#find the hotel with more no of ratings in Banglore?
select Hotel_name,Rating from oyo_db
where Place = 'Bangalore'
Order by Rating desc
limit 1;

#Find hotels with a price between 2000 and 3000 in Delhi with Rating?
select Hotel_name,Price,Rating,Place
from oyo_db
where Price Between 2000 and 3000
And Place='Delhi';

#Find hotels with a maximum stay of more than 3 nights 
select Hotel_name, Minimum_stay
from oyo_db
where Minimum_stay >3
order by minimum_stay Desc;

#Find hotels with a manimum stay of 3 nights or less
select Hotel_name, Minimum_stay
from oyo_db
where Minimum_stay <=3
order by minimum_stay asc;

#Find hotels with a discount of more than 70%?
select Hotel_name,Discount
from oyo_db
where Discount >='70%';

#Find hotels with air conditioning and a minimum stay of 2 nights?
SELECT Hotel_Name
FROM oyo_db
WHERE 'Air Conditioning' = 'YES' AND Minimum_Stay >= 2;
